### ISSUE TITLE
integration with Jeeliz AR

### ISSUE THREAD

**Issue by sandys** [digitallysavvy/AgoraWebXR#6]
hi,
sorry to open this bug here, but we have been struggling to get Agora video calling working with any face filter AR.

https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos

jeeliz integrates well with threejs/babylon, etc. Is there any way to get this to work ? even if it is hacky

**Comment by digitallysavvy** [comment]
@sandys what is the functionality that you are looking to achieve with Agora and Jeeliz? do you want to use the composited canvas output as the stream for Agora?

**Comment by sandys** [comment]
Yes! Absolutely

**Comment by digitallysavvy** [comment]
To use Agora with Jeeliz or any AR library that draws to a canvas element, you will need to use the canvas as the video source for the local stream. 

For example:
```
 let canvas = document.getElementById('canvas');
 let canvasStream = canvas.captureStream(60);
 var localStream = AgoraRTC.createStream({
  video: true,
  audio: true,
  videoSource: canvasStream,
});
```

**Comment by digitallysavvy** [comment]
@sandys I'm going to close this issue, if you have any further issues feel free to open update this issue.
